# Workflow [ No identation required for naming the workflow]
# Should Have Name
name: hello
#on tells when the workflow should run ( give identation by tab)
on: 
  workflow_dispach: 
# Jobs
# Should be inside the workflow
#job tells what the workflow should be, there can be one or more than one jobs , hence we write jobs
#job is an object so needs identation
jobs:  
#1st job  (give identation)
  say-hello:
   #creates an ephermeral container with ubuntu running
    runs-on: ubuntu:latest
    steps:
      - name: Say hello to everyone
        run: echo "hello dosto"
# Steps
# Should be insite the job

# Actions
# Should be inside the Steps
